name: build

on:
  workflow_call:
    inputs:
      addRepoDeps:
        description: 'Add repository from dependencies'
        default: false
        required: false
        type: boolean
jobs:
  helm:
    uses: onecx-apps/ci-common/.github/workflows/helm-build.yml@v2
    secrets: inherit
    with:
      push: true
      artifact: ''    
      helmdir: 'helm'
      helmAbsoluteDir: true
      addRepoDeps: ${{ inputs.addRepoDeps }}
      templateValuesYaml: 'product.version={{ .Version }},product.name={{ .Name }}'