name: release

on:
  workflow_call:

jobs:
  helm:
    uses: onecx-apps/ci-common/.github/workflows/helm-release.yml@v2
    secrets: inherit
  changelog:
    uses: onecx-apps/ci-common/.github/workflows/generate-changelog.yml@v2
    needs: helm
    secrets: inherit